[workspace]

members = [
    'meillionen-mt',
    'meillionen-mt-derive',
    'simplecrop-core',
    'simplecrop-cli',
    'simplecrop-cli-python',
    'simplecrop-lib',
]

#exclude = [
#    'simplecrop-cli-python'
#]
