name: simplecrop-cli
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - pandas
  - compilers
  - jupyterlab
  - landlab
  - hdf5
  - libnetcdf
  - netcdf4
  - pip
  - pip:
    - jupyter-book
