name: simplecrop-cli
channels:
  - conda-forge
dependencies:
  - python=3.8
  - landlab=2.3.0
  - jupytext
  - netCDF4=1.5.6
  - numpy
  - pandas=1.2.4
  - prefect==0.14.19
  - pyarrow==4.0.0
  - pydantic==1.8.2
  - python-flatbuffers==2.0
  - pip
  - pip:
    - -i https://test.pypi.org/simple/
    - meillionen==0.1.5
    - simplecrop-omf==0.1.5
  - simplecrop=0.2.1
  - xarray=0.18.2
