[package]
name = "meillionen-mt"
version = "0.1.0"
authors = ["Calvin Pritchard <pritchard.calvin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.0"
ndarray = "0.13.1"
numpy = "0.11.0"
pyo3 = "0.11.1"