name: Test Meillionen Packages

on:
  push:
    paths-ignore:
    - 'meillionen-docs/**'
    - 'notebooks/**' 

jobs:
  build:
    name: Test Packages
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: sudo apt-get install -y gfortran python3
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set Rust Version to Unstable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: nightly
      - name: Test Workspace
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path examples/crop-pipeline/simplecrop/Cargo.toml --no-default-features
